"""Alert -> actionable insight generator.

Uses AWS Bedrock Mistral (same model + call style as the EC2 api_server)
to turn a structured weather/emergency alert into a short, farmer-friendly
actionable insight in the farmer's language. Falls back to rule-based text
when Bedrock is unavailable or the model errors, so the nightly cron never
dies on a transient LLM failure.
"""

from __future__ import annotations

import json
import os
from typing import Any

from .config import LANG_NAMES

BEDROCK_REGION = os.environ.get("AWS_REGION", "ap-south-1")
BEDROCK_MODEL = os.environ.get("BEDROCK_MODEL_ID", "mistral.mistral-large-3-675b-instruct")

_LANG_INSTRUCTION = {
    "hi": "Write the final insight in Hindi (Devanagari script).",
    "kn": "Write the final insight in Kannada (Kannada script).",
    "te": "Write the final insight in Telugu (Telugu script).",
    "ta": "Write the final insight in Tamil (Tamil script).",
    "mr": "Write the final insight in Marathi (Devanagari script).",
    "en": "Write the final insight in English.",
}

_LIVESTOCK_GUIDANCE: dict[str, list[str]] = {
    "high": [
        "Move livestock to covered shelter before evening.",
        "Keep dry fodder and clean drinking water stocked for 24-48 hours.",
        "Keep weak, young and pregnant animals closest to shelter.",
        "Keep emergency veterinary contacts handy.",
    ],
    "medium": [
        "Keep bedding dry and check roof and drainage.",
        "Reduce long grazing trips during rain or wind hours.",
        "Watch appetite and stress signs in lambs/kids.",
    ],
    "low": [
        "Continue routine care and hydration.",
        "Check the forecast again tomorrow.",
    ],
}


def _rule_based_insight(alert: dict[str, Any], district: str, language: str) -> str:
    level = str(alert.get("level") or "low")
    reasons = alert.get("reasons") or []
    reasons_text = "; ".join(reasons) if reasons else "weather conditions"
    guidance = _LIVESTOCK_GUIDANCE.get(level, _LIVESTOCK_GUIDANCE["low"])
    lang_note = f"({LANG_NAMES.get(language, 'English')} text not generated by LLM; shown in English.)" if language != "en" else ""
    return (
        f"Alert for {district}: {reasons_text}. "
        + " ".join(guidance)
        + (f" {lang_note}" if lang_note else "")
    )


def _invoke_bedrock(prompt: str) -> str | None:
    try:
        import boto3
        client = boto3.client("bedrock-runtime", region_name=BEDROCK_REGION)
        body = json.dumps({
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": 512,
            "temperature": 0.2,
            "top_p": 0.9,
        })
        resp = client.invoke_model(
            modelId=BEDROCK_MODEL,
            body=body,
        )
        result = json.loads(resp["body"].read())
        content = result.get("choices", [{}])[0].get("message", {}).get("content", "")
        return (content or "").strip() or None
    except Exception:
        return None


def generate_alert_insight(
    alert: dict[str, Any],
    district: str,
    language: str = "en",
    *,
    include_livestock_guidance: bool = True,
) -> str:
    """Return an actionable insight string for a single alert record."""
    level = str(alert.get("level") or "low")
    reasons = alert.get("reasons") or []
    reasons_text = "; ".join(reasons) if reasons else "adverse weather"
    lang_instruction = _LANG_INSTRUCTION.get(language, _LANG_INSTRUCTION["en"])
    lang_note = LANG_NAMES.get(language, "English")

    prompt = (
        "You are a practical livestock weather advisor for smallholder sheep and goat farmers in India.\n"
        f"Location: {district} district.\n"
        f"Alert level: {level}.\n"
        f"Alert reason: {reasons_text}.\n"
        "Write a very short actionable insight (2-3 sentences, max 90 words). "
        "Tell the farmer exactly what to do today/tomorrow to protect sheep and goats "
        "(shelter, fodder, water, grazing timing, weak animals). "
        "No markdown, no preamble, no bullet symbols.\n"
        f"{lang_instruction}"
    )
    if include_livestock_guidance:
        prompt += (
            "\nCover these points if relevant:\n- "
            + "\n- ".join(_LIVESTOCK_GUIDANCE.get(level, _LIVESTOCK_GUIDANCE["low"]))
        )

    insight = _invoke_bedrock(prompt)
    if insight:
        return insight
    return _rule_based_insight(alert, district, language)


def generate_digest_insight(
    advisory: str,
    district: str,
    language: str = "en",
) -> str:
    """Turn a raw ICAR agromet advisory snippet into a farmer insight."""
    if not advisory:
        return f"No district agromet advisory published yet for {district}."
    lang_instruction = _LANG_INSTRUCTION.get(language, _LANG_INSTRUCTION["en"])
    prompt = (
        "You are an agricultural advisory translator for Indian livestock farmers.\n"
        f"Here is an official agromet advisory for {district} district:\n{advisory}\n"
        "Summarize the 2 most actionable points for sheep/goat farmers in simple words. "
        "Max 70 words. No markdown, no preamble.\n"
        f"{lang_instruction}"
    )
    insight = _invoke_bedrock(prompt)
    if insight:
        return insight
    return advisory
